SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE >= 20 AND AGE <= 29 AND YEAR(JOINED) = "2021"


-- 다른 사람 풀이
-- SELECT
-- COUNT(*)
-- FROM USER_INFO
-- WHERE JOINED LIKE '2021%'
-- AND AGE BETWEEN 20 AND 29